---

- name: Install laserweb_extra_packages
  apt:
    name: "{{ laserweb_extra_packages }}"
    state: present

- name: Include tasks/build.yml
  include: "build.yml"

- name: Create laserweb_group
  group:
    name: "{{ laserweb_group }}"

- name: Create laserweb_user
  user:
    name: "{{ laserweb_user }}"
    group: "{{ laserweb_group }}"
    groups: "{{ laserweb_extra_groups }}"
    create_home: no
    comment: LaserWeb user
    home: "{{ laserweb_backend_dir }}"

- name: Create systemd service file
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ laserweb_service }}.service"
  register: __laserweb_systemd_config

- name: Reload systemd (daemon-reload)
  command: systemctl daemon-reload
  when: __laserweb_systemd_config.changed

- name: Eanble laserweb_service
  service:
    name: "{{ laserweb_service }}"
    enabled: yes
