---
# tasks file for ansible-role-laserweb

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include tasks/install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Start laserweb_service
  service:
    name: "{{ laserweb_service }}"
    state: started

- name: Wait for laserweb_service
  wait_for:
    delay: 10
    host: "{{ laserweb_hosts | first }}"
    port: "{{ laserweb_port }}"
