---
# tasks file for ansible-role-laserweb

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Start laserweb_service
  service:
    name: "{{ laserweb_service }}"
    state: started

- name: Wait for laserweb_service
  wait_for:
    delay: 10
    host: "{{ laserweb_host }}"
    port: "{{ laserweb_port }}"
